/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Business.ProductBusiness;
import Domain.Provider;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Kenneth
 */
public class MainWindow extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form MainWindow
     */
    
    private ProductBusiness productBusiness;
    public MainWindow() {
        initComponents();
        
        this.productBusiness = new ProductBusiness();
        ArrayList<Provider> list = this.productBusiness.getProviders();
        for (int i = 0; i < list.size(); i++) {
           this.providerComboBox.addItem(list.get(i));
        }
        
        this.manageProductBtn.addActionListener(this);
        this.exitBtn.addActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcomeLb = new javax.swing.JLabel();
        manageProductBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        selectLb = new javax.swing.JLabel();
        providerComboBox = new javax.swing.JComboBox<>();

        setForeground(new java.awt.Color(0, 0, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setForeground(new java.awt.Color(0, 51, 255));

        welcomeLb.setBackground(new java.awt.Color(255, 255, 255));
        welcomeLb.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        welcomeLb.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLb.setText("Sistema administrativo");

        manageProductBtn.setBackground(new java.awt.Color(0, 102, 204));
        manageProductBtn.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        manageProductBtn.setForeground(new java.awt.Color(0, 0, 0));
        manageProductBtn.setText("Administrar productos");
        manageProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductBtnActionPerformed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(0, 102, 204));
        exitBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(0, 0, 0));
        exitBtn.setText("Salir");

        selectLb.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        selectLb.setText("Seleccione el proveedor");

        providerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(welcomeLb, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageProductBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(providerComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(selectLb, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(welcomeLb, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(selectLb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(providerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(manageProductBtn)
                .addGap(27, 27, 27)
                .addComponent(exitBtn)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void providerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_providerComboBoxActionPerformed

    private void manageProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageProductBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageProductBtn;
    private javax.swing.JComboBox<Provider> providerComboBox;
    private javax.swing.JLabel selectLb;
    private javax.swing.JLabel welcomeLb;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
         if (ae.getSource().equals(manageProductBtn)) {
             
              Provider p = (Provider)this.providerComboBox.getSelectedItem();
              if(p!=null){
                  ManageProductWindow m = new  ManageProductWindow(p.getId());
              }else{
                  JOptionPane.showMessageDialog(null,"No existen proveedores");
              }
              
         }
         
         if (ae.getSource().equals(exitBtn)) {
             System.exit(0);
         }
        
         
    }
}
