/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Business.ProductBusiness;
import Domain.Product;
import Domain.Provider;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Kenneth
 */
public class ManageProductWindow extends javax.swing.JFrame {

   
    private Provider provider;
    
    private ProductBusiness productBusiness;
    private ArrayList<Product> productList;

    public ManageProductWindow(Provider provider) {
        initComponents();
        this.provider = provider;
        this.welcomeLb3.setText(this.welcomeLb3.getText()+" de "+this.provider.getName());
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        welcomeLb3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));
        jPanel4.setForeground(new java.awt.Color(0, 51, 255));

        welcomeLb3.setBackground(new java.awt.Color(255, 255, 255));
        welcomeLb3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        welcomeLb3.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLb3.setText("Productos ");

        productTable.setBackground(new java.awt.Color(0, 153, 204));
        productTable.setRowHeight(30);
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(0).setHeaderValue("ID");
            productTable.getColumnModel().getColumn(1).setHeaderValue("NOMBRE");
            productTable.getColumnModel().getColumn(2).setHeaderValue("DESCRIPCIÓN");
            productTable.getColumnModel().getColumn(3).setHeaderValue("PRECIO");
            productTable.getColumnModel().getColumn(4).setHeaderValue("ACCIÓN");
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(welcomeLb3, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(welcomeLb3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        int column = this.productTable.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/this.productTable.getRowHeight();
        
        Object value = this.productTable.getValueAt(row, column);
        if(value instanceof JButton){
            ((JButton) value).doClick();
            JButton boton = (JButton) value;
            if(boton.getName().equals("1")){
               this.productBusiness.updateProductStatus(this.provider.getId(),(int)this.productTable.getValueAt(row, 0),0);
            }else{
                this.productBusiness.updateProductStatus(this.provider.getId(),(int)this.productTable.getValueAt(row, 0),1);
            }
            this.init();
        }
    }//GEN-LAST:event_productTableMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public void init() {
        this.productBusiness = new ProductBusiness();
        this.productList = new ArrayList<>();
        this.productList = this.productBusiness.getProducts(this.provider);
        this.productTable.setDefaultRenderer(Object.class, new Render());
        
        
       JButton ocultar;
       DefaultTableModel d = new DefaultTableModel(
               null,
               new Object[] {"ID","NOMBRE","DESCRIPCION","PRECIO","ACCION"}
       ){
           public boolean isCellEditable(int row, int column){
               return false;
           }
       }
        ;
       this.productTable.setModel(d);
        
      
        DefaultTableModel model = (DefaultTableModel) this.productTable.getModel();
        for (int i = 0; i < this.productList.size(); i++) {
            Product p = this.productList.get(i);
            
            if(p.getStatus()==1){
                ocultar  = new JButton("Ocultar");
            }else{
                ocultar  = new JButton("Mostrar");
            }
            
            ocultar.setName(String.valueOf(p.getStatus()));
            model.addRow(new Object[]{p.getId(),p.getName(), p.getDescription(),p.getPrice(),ocultar});
        }
        
       
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProductWindow(new Provider()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTable;
    private javax.swing.JLabel welcomeLb3;
    // End of variables declaration//GEN-END:variables
}
